<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>3600</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1234d0d0-63ca-4083-9131-470469bc53c1</testSuiteGuid>
   <testCaseLink>
      <guid>46485d8b-b606-470b-a669-8d808f06be49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/alterra/Login/Login with valid credential with Variable</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8ed1c0c3-ac09-4ef6-a94e-1d19e71fb4f7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/alterra/LoginDataAlterra</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8ed1c0c3-ac09-4ef6-a94e-1d19e71fb4f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cb074bd4-29ad-4046-b095-2d41e8217003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8ed1c0c3-ac09-4ef6-a94e-1d19e71fb4f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c813eaaa-70c4-4b01-a9b0-79e4416d6cfc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
