<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login-DDT-ForLoop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6561635a-adaf-4831-a111-4f8b8df80809</testSuiteGuid>
   <testCaseLink>
      <guid>de7b71a2-b360-411b-8974-56d4dfe5785e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Contekan/TC Manual/Scenario/Login/Login Positive Flow-DDT-TestCase(ForLoop)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b37bdb46-dbb9-448e-a9da-2848a30ddde6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54d1c4db-b305-4d39-b450-d82f519c9aa0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
