<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login with Failed</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ae5f849e-00b4-4632-8635-43b2d170e98e</testSuiteGuid>
   <testCaseLink>
      <guid>c07c333f-0286-4701-8324-29be1fff1eab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Contekan/TC Manual/Scenario/Login/Login Positive Flow-Single</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5645d16e-d2d6-440a-9622-1c93ee72f12e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e72c9601-c116-49b9-b949-c58c8a5b7582</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77dc38a8-0c53-4e5a-a2fa-5815b890b40c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Contekan/TC Failed and Error Test Case/Failed-Login Flow-Single</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72ccefef-c910-4f02-b2a3-5cce5b00afeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361f4a05-dbdb-4175-b86a-72670b928232</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92810a3f-3dc5-4f19-b874-8c7c5a88e723</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/alterra/Login/Login with valid credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb079d9d-1308-4b26-8599-8e96f05a8418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45044473-6516-419e-bb23-89cc58602462</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
